const PRODUCTS_KEY='smash-burger-products';
const CART_KEY='smash-burger-cart';
const CHECKOUT_KEY='smash-burger-checkout-url';
const $=selector=>document.querySelector(selector);
const initialProducts=[
  {id:'smoked-smash',name:'سموك سماش برجر',price:115,category:'برجر',description:'لحم سماش مدخن مع جبنة وصوص خاص.',image:'images/WhatsApp Image 2026-09-07 at 1.42.01 AM.jpeg',sizes:[{name:'Single Burger',price:115},{name:'Double Burger',price:140},{name:'Triple Burger',price:165},{name:'Quarter Burger',price:190}],addons:[{name:'جبنة إضافية',price:15},{name:'صوص ليتشي',price:10}]},
  {id:'chicken-crunchy',name:'تشيكن كرنشي',price:95,category:'وجبات',description:'دجاج كرنشي طازج ومقرمش.',image:'images/WhatsApp Image 2026-09-07 at 1.42.02 AM.jpeg',sizes:[],addons:[{name:'صوص إضافي',price:10}]},
  {id:'double-cheese',name:'دبل تشيز برجر',price:140,category:'برجر',description:'قطعتان لحم مع جبنة مضاعفة.',image:'images/WhatsApp Image 2026-09-07 at 1.42.03 AM.jpeg',sizes:[{name:'Double Burger',price:140}],addons:[{name:'جبنة إضافية',price:15}]},
  {id:'crispy-fries',name:'بطاطس كرنشي',price:55,category:'جانبية',description:'بطاطس ذهبية مقرمشة.',image:'images/WhatsApp Image 2026-09-07 at 1.42.36 AM.jpeg',sizes:[],addons:[{name:'صوص جبنة',price:15}]}
];
const getProducts=()=>JSON.parse(localStorage.getItem(PRODUCTS_KEY)||'null')||initialProducts;
const saveProducts=products=>localStorage.setItem(PRODUCTS_KEY,JSON.stringify(products));
let previewImage='';

const sectionCategories={mix:'كريب',regular:'وجبات',smash:'برجر',box:'جانبية',fries:'جانبية',sandwich:'وجبات','chicken-sandwich':'وجبات','pizza-roll':'بيتزا',pizza:'بيتزا',extra:'جانبية'};
const menuImages=['images/WhatsApp Image 2026-09-07 at 1.42.01 AM.jpeg','images/WhatsApp Image 2026-09-07 at 1.42.02 AM.jpeg','images/WhatsApp Image 2026-09-07 at 1.42.03 AM.jpeg','images/WhatsApp Image 2026-09-07 at 1.42.36 AM.jpeg','images/WhatsApp Image 2026-09-07 at 1.43.05 AM.jpeg'];
function menuProduct(card,index){const name=card.querySelector('h3')?.textContent.trim();if(!name)return null;const section=card.closest('.section')?.dataset.section;const sizes=[...card.querySelectorAll('.pill')].map(pill=>({name:pill.textContent.replace(/[0-9]/g,'').trim(),price:Number(pill.querySelector('b')?.textContent||0)})).filter(size=>size.price);const price=Number((card.querySelector('.price')?.textContent||sizes[0]?.price||0).replace(/\D/g,''));return {id:`menu-${index}-${name.replace(/\s+/g,'-')}`,name,price,category:sectionCategories[section]||'وجبات',description:card.querySelector('.desc')?.textContent.trim()||'',image:menuImages[index%menuImages.length],sizes,addons:[{name:'جبنة إضافية',price:15},{name:'صوص إضافي',price:10}]}}
async function importMenuProducts(){try{const response=await fetch('index.html',{cache:'no-store'});if(!response.ok)return;const documentSource=new DOMParser().parseFromString(await response.text(),'text/html');const imported=[...documentSource.querySelectorAll('.section .card')].map(menuProduct).filter(Boolean);if(!imported.length)return;const saved=JSON.parse(localStorage.getItem(PRODUCTS_KEY)||'[]');const byName=new Map(saved.map(product=>[product.name,product]));imported.forEach(product=>{if(!byName.has(product.name)){saved.push(product);byName.set(product.name,product)}});saveProducts(saved.length?saved:initialProducts)}catch(error){console.warn('Could not import current menu products.',error)}}

function row(kind,item={name:'',price:''}){return `<div class="repeat-row"><input data-${kind}-name placeholder="الاسم" value="${item.name}"><input data-${kind}-price type="number" min="0" placeholder="السعر" value="${item.price}"><button type="button" class="tiny-button remove-row">×</button></div>`}
function bindRows(){document.querySelectorAll('.remove-row').forEach(button=>button.onclick=()=>button.parentElement.remove())}
function addRow(kind,item){document.querySelector(`#${kind}s`).insertAdjacentHTML('beforeend',row(kind,item));bindRows()}
function resetForm(){$('#product-form').reset();$('#product-id').value='';$('#sizes').innerHTML='';$('#addons').innerHTML='';$('#image-preview').style.display='none';previewImage='';$('#form-title').textContent='إضافة صنف جديد';$('#cancel-edit').hidden=true}
function fields(kind){return [...document.querySelectorAll(`[data-${kind}-name]`)].map((input,index)=>({name:input.value.trim(),price:Number(document.querySelectorAll(`[data-${kind}-price]`)[index].value)})).filter(item=>item.name&&Number.isFinite(item.price))}
function render(){const products=getProducts(),cart=JSON.parse(localStorage.getItem(CART_KEY)||'[]');$('#products-count').textContent=products.length;$('#categories-count').textContent=new Set(products.map(product=>product.category)).size;$('#cart-count').textContent=cart.reduce((sum,item)=>sum+item.quantity,0);$('#product-list').innerHTML=products.length?products.map(product=>`<article class="admin-product"><img src="${product.image||''}" alt="${product.name}"><div><h3>${product.name}</h3><p>${product.category} · ${product.description||'بدون وصف'}</p><strong>${product.price} جنيه</strong></div><div class="row-actions"><button class="edit" data-edit="${product.id}">تعديل</button><button class="delete" data-delete="${product.id}">حذف</button></div></article>`).join(''):'<p>لا توجد أصناف حاليًا.</p>';document.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>editProduct(button.dataset.edit));document.querySelectorAll('[data-delete]').forEach(button=>button.onclick=()=>{if(confirm('حذف هذا الصنف من المنيو؟')){saveProducts(getProducts().filter(product=>product.id!==button.dataset.delete));render()}})}
function editProduct(id){const product=getProducts().find(item=>item.id===id);if(!product)return;$('#product-id').value=product.id;$('#name').value=product.name;$('#price').value=product.price;$('#category').value=product.category;$('#description').value=product.description||'';previewImage=product.image||'';if(previewImage){$('#image-preview').src=previewImage;$('#image-preview').style.display='block'}$('#sizes').innerHTML='';$('#addons').innerHTML='';product.sizes.forEach(item=>addRow('size',item));product.addons.forEach(item=>addRow('addon',item));$('#form-title').textContent='تعديل الصنف';$('#cancel-edit').hidden=false;window.scrollTo({top:0,behavior:'smooth'})}
$('#add-size').onclick=()=>addRow('size');$('#add-addon').onclick=()=>addRow('addon');$('#cancel-edit').onclick=resetForm;
$('#image').onchange=event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{previewImage=reader.result;$('#image-preview').src=previewImage;$('#image-preview').style.display='block'};reader.readAsDataURL(file)};
$('#product-form').onsubmit=event=>{event.preventDefault();const id=$('#product-id').value||`product-${Date.now()}`;const products=getProducts();const existing=products.findIndex(product=>product.id===id);const current=existing>-1?products[existing]:{};const product={...current,id,name:$('#name').value.trim(),price:Number($('#price').value),category:$('#category').value,description:$('#description').value.trim(),image:previewImage||current.image||'',sizes:fields('size'),addons:fields('addon')};if(existing>-1)products[existing]=product;else products.unshift(product);saveProducts(products);resetForm();render()};
$('#save-settings').onclick=()=>{localStorage.setItem(CHECKOUT_KEY,$('#checkout-url').value.trim());alert('تم حفظ رابط إتمام الطلب.')};$('#checkout-url').value=localStorage.getItem(CHECKOUT_KEY)||'';$('#logout').onclick=()=>{sessionStorage.removeItem('smash-burger-admin-access');location.href='staff-access.html'};(async()=>{await importMenuProducts();render()})();
