const PRODUCTS_KEY='smash-burger-products';
const CART_KEY='smash-burger-cart';
const $=selector=>document.querySelector(selector);
document.head.insertAdjacentHTML('beforeend','<style>.settings{display:none!important}</style>');
document.querySelector('.settings')?.remove();
const menuImages=['images/WhatsApp Image 2026-09-07 at 1.42.01 AM.jpeg','images/WhatsApp Image 2026-09-07 at 1.42.02 AM.jpeg','images/WhatsApp Image 2026-09-07 at 1.42.03 AM.jpeg','images/WhatsApp Image 2026-09-07 at 1.42.36 AM.jpeg','images/WhatsApp Image 2026-09-07 at 1.43.05 AM.jpeg'];
const catalog=[
['الوحش',130,'كريب'],['الصاروخ',130,'كريب'],['بلو استربس',130,'كريب'],['ميكس دجاج',120,'كريب'],['ميكس ميت',120,'كريب'],['كريب ليتشي',120,'كريب'],['فيرال تيستي',120,'كريب'],['هالبينو تشيكن رانش',120,'كريب'],
['زنجر سوبريم',105,'وجبات'],['ميكس جبن',80,'وجبات'],['كريب البطاطس',60,'وجبات'],['تشيكن رانش',110,'وجبات'],['كوردن بلو',110,'وجبات'],['فرايداي',110,'وجبات'],['تشيكن كرسبي',80,'وجبات'],['تشيكن باربكيو',110,'وجبات'],['شيش طاووق',110,'وجبات'],['بانيه',80,'وجبات'],['سو تشيلي',110,'وجبات'],['سوبر كرانشي',105,'وجبات'],
['سماش برجر كلاسيك',115,'برجر'],['سموكد سماش برجر',120,'برجر'],['الوحش فرايز',80,'جانبية'],['تشيكن فرايز',70,'جانبية'],['سماش فرايز',80,'جانبية'],['هالبينو تشيز فرايز',75,'جانبية'],['تيستي فرايز',85,'جانبية'],['بطاطس',25,'جانبية'],['بطاطس شيدر',35,'جانبية'],['بطاطس صوص',35,'جانبية'],
['بطاطس',30,'وجبات'],['بطاطس شيدر',35,'وجبات'],['بطاطس هوت دوج',60,'وجبات'],['فرايداي',85,'وجبات'],['تشيكن فاهيتا',85,'وجبات'],['تشيكن بانيه',70,'وجبات'],['زنجر سوبريم',80,'وجبات'],['سوبر كرانشي',85,'وجبات'],['برجر دجاج مدخن',120,'وجبات'],['مشروم رانش',130,'وجبات'],['عشاق الجبن',130,'وجبات'],['تشيكن ليتشي',130,'وجبات'],
['تشيكن رانش',120,'بيتزا'],['تشيكن باربكيو',120,'بيتزا'],['تشيكن & تشيز',120,'بيتزا'],['تشيكن كرانشي',120,'بيتزا'],['سوبر ليتشي',120,'بيتزا'],['بيتزا مارجريتا',145,'بيتزا'],['بيتزا تشيكن رانش',160,'بيتزا'],['بيتزا تشيكن باربكيو',165,'بيتزا'],['بيتزا بيبروني',165,'بيتزا'],['بيتزا لحمة مفرومة',160,'بيتزا'],['بيتزا نص ونص',175,'بيتزا'],['سوبر كرانشي',170,'بيتزا'],['كواترو فورماجي',175,'بيتزا'],['سجق مدخن',165,'بيتزا'],['هوت دوج مدخن',155,'بيتزا'],['ميكس تشيكن',160,'بيتزا'],['سوبر ليتشي',170,'بيتزا'],
['صوص',15,'جانبية'],['كول سلو',15,'جانبية'],['مخلل',15,'جانبية'],['إيجيبتين صودا',20,'جانبية'],['كومبو',35,'جانبية']
];
const initialProducts=catalog.map(([name,price,category],index)=>({id:`menu-${index}`,name,price,category,description:'',image:menuImages[index%menuImages.length],sizes:[],addons:[{name:'جبنة إضافية',price:15},{name:'صوص إضافي',price:10}]}));
const getProducts=()=>JSON.parse(localStorage.getItem(PRODUCTS_KEY)||'null')||initialProducts;
const saveProducts=products=>localStorage.setItem(PRODUCTS_KEY,JSON.stringify(products));
let previewImage='';
let activeCategory='الكل';
let searchTerm='';

const sectionCategories={mix:'كريب',regular:'وجبات',smash:'برجر',box:'جانبية',fries:'جانبية',sandwich:'وجبات','chicken-sandwich':'وجبات','pizza-roll':'بيتزا',pizza:'بيتزا',extra:'جانبية'};
function menuProduct(card,index){const name=card.querySelector('h3')?.textContent.trim();if(!name)return null;const section=card.closest('.section')?.dataset.section;const sizes=[...card.querySelectorAll('.pill')].map(pill=>({name:pill.textContent.replace(/[0-9]/g,'').trim(),price:Number(pill.querySelector('b')?.textContent||0)})).filter(size=>size.price);const price=Number((card.querySelector('.price')?.textContent||sizes[0]?.price||0).replace(/\D/g,''));return {id:`menu-${index}`,name,price,category:sectionCategories[section]||'وجبات',description:card.querySelector('.desc')?.textContent.trim()||'',image:menuImages[index%menuImages.length],sizes,addons:[{name:'جبنة إضافية',price:15},{name:'صوص إضافي',price:10}]}}
async function importMenuProducts(){const saved=JSON.parse(localStorage.getItem(PRODUCTS_KEY)||'[]');const known=new Set(saved.map(product=>product.id));initialProducts.forEach(product=>{if(!known.has(product.id)){saved.push(product);known.add(product.id)}});try{const response=await fetch('index.html',{cache:'no-store'});if(response.ok){const documentSource=new DOMParser().parseFromString(await response.text(),'text/html');[...documentSource.querySelectorAll('.section .card')].map(menuProduct).filter(Boolean).forEach(product=>{if(!known.has(product.id)){saved.push(product);known.add(product.id)}})}}catch(error){console.warn('Using bundled menu catalog.',error)}saveProducts(saved)}

function row(kind,item={name:'',price:''}){return `<div class="repeat-row"><input data-${kind}-name placeholder="الاسم" value="${item.name}"><input data-${kind}-price type="number" min="0" placeholder="السعر" value="${item.price}"><button type="button" class="tiny-button remove-row">×</button></div>`}
function bindRows(){document.querySelectorAll('.remove-row').forEach(button=>button.onclick=()=>button.parentElement.remove())}
function addRow(kind,item){document.querySelector(`#${kind}s`).insertAdjacentHTML('beforeend',row(kind,item));bindRows()}
function resetForm(){$('#product-form').reset();$('#product-id').value='';$('#sizes').innerHTML='';$('#addons').innerHTML='';$('#image-preview').style.display='none';previewImage='';$('#form-title').textContent='إضافة صنف جديد';$('#cancel-edit').hidden=true}
function fields(kind){return [...document.querySelectorAll(`[data-${kind}-name]`)].map((input,index)=>({name:input.value.trim(),price:Number(document.querySelectorAll(`[data-${kind}-price]`)[index].value)})).filter(item=>item.name&&Number.isFinite(item.price))}
function render(){const products=getProducts(),cart=JSON.parse(localStorage.getItem(CART_KEY)||'[]'),categories=['الكل',...new Set(products.map(product=>product.category))],visible=products.filter(product=>(activeCategory==='الكل'||product.category===activeCategory)&&`${product.name} ${product.description||''}`.toLowerCase().includes(searchTerm));$('#products-count').textContent=products.length;$('#categories-count').textContent=new Set(products.map(product=>product.category)).size;$('#cart-count').textContent=cart.reduce((sum,item)=>sum+item.quantity,0);$('#product-filters').innerHTML=categories.map(category=>`<button class="filter-button ${category===activeCategory?'active':''}" data-category="${category}">${category}</button>`).join('');$('#product-list').innerHTML=visible.length?visible.map(product=>`<article class="admin-product"><img src="${product.image||''}" alt="${product.name}"><div><h3>${product.name}</h3><p>${product.category} · ${product.description||'بدون وصف'}</p><strong>${product.price} جنيه</strong></div><div class="row-actions"><button class="edit" data-edit="${product.id}">تعديل</button><button class="delete" data-delete="${product.id}">حذف</button></div></article>`).join(''):'<p class="no-products">لا توجد أصناف مطابقة للبحث.</p>';document.querySelectorAll('[data-category]').forEach(button=>button.onclick=()=>{activeCategory=button.dataset.category;render()});document.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>editProduct(button.dataset.edit));document.querySelectorAll('[data-delete]').forEach(button=>button.onclick=()=>{if(confirm('حذف هذا الصنف من المنيو؟')){saveProducts(getProducts().filter(product=>product.id!==button.dataset.delete));render()}})}
function editProduct(id){const product=getProducts().find(item=>item.id===id);if(!product)return;$('#product-id').value=product.id;$('#name').value=product.name;$('#price').value=product.price;$('#category').value=product.category;$('#description').value=product.description||'';previewImage=product.image||'';if(previewImage){$('#image-preview').src=previewImage;$('#image-preview').style.display='block'}$('#sizes').innerHTML='';$('#addons').innerHTML='';product.sizes.forEach(item=>addRow('size',item));product.addons.forEach(item=>addRow('addon',item));$('#form-title').textContent='تعديل الصنف';$('#cancel-edit').hidden=false;window.scrollTo({top:0,behavior:'smooth'})}
$('#add-size').onclick=()=>addRow('size');$('#add-addon').onclick=()=>addRow('addon');$('#cancel-edit').onclick=resetForm;
$('#image').onchange=event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{previewImage=reader.result;$('#image-preview').src=previewImage;$('#image-preview').style.display='block'};reader.readAsDataURL(file)};
$('#product-form').onsubmit=event=>{event.preventDefault();const id=$('#product-id').value||`product-${Date.now()}`;const products=getProducts();const existing=products.findIndex(product=>product.id===id);const current=existing>-1?products[existing]:{};const product={...current,id,name:$('#name').value.trim(),price:Number($('#price').value),category:$('#category').value,description:$('#description').value.trim(),image:previewImage||current.image||'',sizes:fields('size'),addons:fields('addon')};if(existing>-1)products[existing]=product;else products.unshift(product);saveProducts(products);resetForm();render()};
$('#logout').onclick=()=>{sessionStorage.removeItem('smash-burger-admin-access');location.href='staff-access.html'};$('#product-list').insertAdjacentHTML('beforebegin','<div class="product-tools"><div id="product-filters" class="product-filters"></div><div class="product-search"><input id="product-search" type="search" placeholder="ابحث باسم الصنف"><button id="run-search" type="button" aria-label="بحث">⌕</button></div></div>');document.head.insertAdjacentHTML('beforeend','<style>.product-tools{display:grid;gap:11px;margin:-5px 0 14px}.product-filters{display:flex;flex-wrap:wrap;gap:7px}.filter-button{border:1px solid #eadfd8;background:#fff;border-radius:8px;padding:8px 10px;color:#554940;font:700 11px Alexandria;cursor:pointer}.filter-button.active{background:#e94824;border-color:#e94824;color:#fff}.product-search{display:flex;gap:7px}.product-search input{flex:1;border:1px solid #eadfd8;border-radius:8px;padding:10px;font:12px Alexandria;outline-color:#e94824}.product-search button{width:42px;border:0;border-radius:8px;background:#fff1eb;color:#e94824;font:800 20px Arial;cursor:pointer}.no-products{text-align:center;color:#806f65;padding:22px}</style>');$('#product-search').addEventListener('input',event=>{searchTerm=event.target.value.trim().toLowerCase();render()});$('#run-search').onclick=()=>{$('#product-search').focus();render()};(async()=>{await importMenuProducts();render()})();
